version: '3.8'

services:
  api:
    container_name: api_monitor
    build:
      context: ./api_monitor
    ports:
      - "5050:5050"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    restart: always

  db:
    container_name: postgres_db
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  agent:
    container_name: monitoring_agent
    build:
      context: ./agent
    depends_on:
      - api
    environment:
      - API_URL=http://api:5050/api/data
    restart: unless-stopped

volumes:
  postgres_data:
